sync

diff --git a/bin/package_installer b/bin/package_installer
--- a/bin/package_installer
+++ b/bin/package_installer
@@ -1,5 +1,19 @@
 #!/usr/bin/env bash
 
+success() {
+    # shellcheck disable=SC2059
+    printf "\r\033[2K  [ \033[00;32mOK\033[0m ] $1\n"
+}
+
+fail() {
+    # shellcheck disable=SC2059
+    printf "\r\033[2K  [\033[0;31mFAIL\033[0m] $1\n"
+    echo ''
+    exit
+}
+
+set -e
+
 echo ""
 echo "> $1"
 
@@ -11,4 +25,4 @@ else
     sudo apt install -qqy "$1"
 fi
 
-exit 0
+[ $? -eq 0 ] && success $1 || fail $1
